version: '3'

services:
  solweig-jobs:
    build: .
    volumes:
      - data-volume:/app/output
    deploy:
      resources:
        limits:
          memory: 1500m
  flask-app:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - data-volume:/app/output
    deploy:
      resources:
        limits:
          memory: 400m
  
volumes:
  data-volume:

