version: '3'

services:
  solweig-jobs:
    build: .
    volumes:
      - data-volume:/app/output
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: '3G'
        reservations:
            cpus: '1.0'
            memory: '1G'
  flask-app:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - data-volume:/app/output
  
volumes:
  data-volume:

